### ISSUE TITLE
Create publiccode.yml

### ISSUE THREAD

**Issue by samuelwei** [THM-Health/PILOS#2005]
See https://docs.italia.it/italia/developers-italia/publiccodeyml-en/en/master/index.html

TODOs

- [x] Create new screenshots and add to readme

**Comment by samuelwei** [comment]
```yaml
publiccodeYmlVersion: "0.4"
name: PILOS
url: https://github.com/THM-Health/PILOS
softwareVersion: 4.3.1
releaseDate: 2025-02-17
logo: https://raw.githubusercontent.com/THM-Health/PILOS/4.x/public/images/logo.svg
platforms:
  - web
categories:
  - video-conferencing
usedBy:
  - Technische Hochschule Mittelhessen
  - Goethe-Universität Frankfurt am Main
  - Universität Innsbruck
  - Kompetenzzentrum für Telemedizin und E-Health Hessen (KTE Hessen)
developmentStatus: stable
softwareType: standalone/web
description:
  en:
    localisedName: PILOS
    shortDescription: PILOS is an easy-to-use open source front-end for
      BigBlueButton servers with a built-in load balancer.
    longDescription: >-
      All in one video conferencing platform powered by BigBlueButton™.

      Designed with education at its core, PILOS offers a seamless, interactive,
      and secure solution for online learning, teaching, and all kinds of
      virtual meetings. Adaptable to your needs, PILOS delivers high-quality
      video, robust collaboration tools, and an intuitive user experience.


      **All you need for a great video conference experience:**

      - **Video and Audio**
        High quality video and audio to foster a more personal and engaging experience.
      - **Collaboration**
        Share your screen, use the interactive multi-user whiteboard, and work together in breakout rooms.
      - **Engagement**
        Engage your audience with interactive tools like chat, emojis, surveys and much more.
      - **Recording**
        Record your videoconferences and make them available using fine grained permission control.
      - **Security**
        All communication data is securely encrypted during transmission using the WebRTC protocol.
      - **Statistics**
        Get detailed reports on the attendance and usage of your videoconferences.
    features:
      - Create video conference rooms
      - Share files for  video conferences
      - Manage BigBlueButton Server and Server Pools
      - Manage users and roles
      - Manage room types (room setting presets)
      - Record video conferences
legal:
  license: LGPL-2.1-only
maintenance:
  type: internal
localisation:
  localisationReady: true
  availableLanguages:
    - de
    - en
    - fr
```
