### ISSUE TITLE
"Meeting running" status label in room overview

### ISSUE THREAD

**Issue by tibroc** [THM-Health/PILOS#253]
**Is your feature request related to a problem? Please describe.**
For remote teams, it happens that you have a "pool" of meeting-rooms (much as in real life) that are used for different purposes. E.g. we also use them for peer programming or breaks. In these cases it is sometimes helpful to see from "the outside" if a room is already occupied or somebody already is present.

**Describe the solution you'd like**
Show if a meeting is already running in the frontend. This could be a very simple sign (like a green or red dot next to the name of the meeting, or a "meeting running" label).

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by tibroc** [comment]
This could either be in the room overview:

![image](https://user-images.githubusercontent.com/39943803/185587208-247f49bc-2c26-4310-b61b-d5d27a25a193.png)

or if these are too many requests for one view, in the room settings:

![image](https://user-images.githubusercontent.com/39943803/185587315-f28b0145-493c-4d75-8fde-4c988f5adba7.png)

**Comment by SamuelWei** [comment]
Mockup for personal start page:
![image](https://user-images.githubusercontent.com/4281791/185587550-ab417da8-39cb-4676-926d-06c7f947ecd2.png)

@tibroc If the room is running, it is already shown in the ui, see this screenshot
![image](https://user-images.githubusercontent.com/4281791/185587897-1c75a8a9-0db6-4bb8-81e1-27f567d0dc3e.png)

**Comment by tibroc** [comment]
Right, so the first one, if technically reasonable.

**Comment by SamuelWei** [comment]
Ideas to implement:

1. Move https://github.com/THM-Health/PILOS/blob/master/app/Http/Resources/Room.php#L63 outside of $this->mergeWhen
2. Add css class to add running indicator:

```css
.room-status:after {
    content: '';
position: absolute;
top: 5px;
right: 5px;
width: 10px;
height: 10px;
border-radius: 50%;
background-color: #ee0000;
}

.room-status.running:after {
background-color: #54af3a;

}
```
3. Bind css classes based on running attribute
